"""Remove unique constraint from user email

Revision ID: 205e4ec441a1
Revises: 246077bc0d59
Create Date: 2025-05-08 13:18:34.620789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '205e4ec441a1'
down_revision = '246077bc0d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_email')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_index('ix_user_email', ['email'], unique=1)

    # ### end Alembic commands ###
